apiVersion: apps/v1
kind: Deployment
metadata:
  name: agente-corporativo-ia
  namespace: agente-corporativo-ia
spec:
  template:
    spec:
      containers:
        - name: app
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 4Gi
        - name: api
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 4Gi
