apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ciudad-analitica
  namespace: ciudad-analitica
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ciudad-analitica.example.com
      secretName: ciudad-analitica-tls
  rules:
    - host: ciudad-analitica.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ciudad-analitica
                port:
                  name: http
