apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: agente-corporativo-ia
    newName: ghcr.io/replace-with-owner/agente-corporativo-ia
    newTag: latest
