apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: chatbot
    newName: ghcr.io/replace-with-owner/chatbot
    newTag: latest
