apiVersion: v1
kind: ConfigMap
metadata:
  name: ciudad-analitica-config
  namespace: ciudad-analitica
data:
  LANGSMITH_TRACING: "true"
  LANGSMITH_PROJECT: "proyecto_coder"
  AGENTE_CORPORATIVO_DB: "/app/data/agente_corporativo.sqlite3"
  CHROMA_PERSIST_DIR: "/app/manuales_complejos_chroma_db"
  KNOWLEDGE_CHROMA_PERSIST_DIR: "/app/manuales_simples_chroma_db"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_PORT: "8501"
