apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: ciudad-analitica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: complex-chroma
  namespace: ciudad-analitica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-chroma
  namespace: ciudad-analitica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
